#!/bin/sh
# SevynOS GRUB configuration generator (shared library).
#
# Generates /boot/grub/grub.cfg for installed systems. Used by
# sevyn-installer-chroot.sh at install time and shipped inside the recovery
# initramfs so recovery can regenerate the bootloader configuration after a
# reinstall. Source this file, then call:
#
#   sevyn_write_grub_cfg <outfile> <root-uuid> [esp-uuid]
#
# When <esp-uuid> is given, the "SevynOS Recovery" entry boots the kernel and
# the recovery initramfs from the ESP (EFI/SevynOS/), so a damaged main
# rootfs cannot prevent recovery from starting. Without an ESP (legacy
# BIOS installs) recovery boots from /boot on the root filesystem.
#
# The recovery entries deliberately pass no root=: the recovery initramfs
# never mounts the main rootfs at boot. The installed-system UUID is passed
# as sevyn.rootuuid= so recovery operations (rollback, reset, …) can locate
# the root partition without mounting it first.
set -eu

sevyn_write_grub_cfg() {
  outfile="$1"
  root_uuid="$2"
  esp_uuid="${3:-}"

  [ -n "$root_uuid" ] || {
    echo "sevyn_write_grub_cfg: root UUID is required" >&2
    return 1
  }

  cat > "$outfile" <<GRUBEOF
# SevynOS GRUB Configuration — Generated by sevyn-installer
insmod part_gpt
insmod ext2
insmod fat
insmod search
insmod search_fs_uuid
insmod all_video

set default=0
set timeout=5

if [ "\$grub_platform" = "pc" ]; then
  set gfxpayload=text
else
  unset gfxpayload
fi

if serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1; then
  terminal_input console serial
  terminal_output console serial
fi

search --no-floppy --set=root --fs-uuid $root_uuid

menuentry "SevynOS" {
  search --no-floppy --set=root --fs-uuid $root_uuid
  linux /boot/vmlinuz root=UUID=$root_uuid rw init=/init console=ttyS0,115200 console=tty0 panic=-1 loglevel=4 modprobe.blacklist=nouveau nouveau.modeset=0 sevyn.installed=1
  initrd /boot/initramfs.cpio.gz
}

menuentry "SevynOS (safe graphics)" {
  search --no-floppy --set=root --fs-uuid $root_uuid
  linux /boot/vmlinuz root=UUID=$root_uuid rw init=/init console=ttyS0,115200 console=tty0 panic=-1 loglevel=4 nomodeset sevyn.gpu=0 modprobe.blacklist=nouveau nouveau.modeset=0 sevyn.installed=1
  initrd /boot/initramfs.cpio.gz
}

menuentry "SevynOS (diagnostic)" {
  search --no-floppy --set=root --fs-uuid $root_uuid
  linux /boot/vmlinuz root=UUID=$root_uuid rw init=/init console=ttyS0,115200 console=tty0 panic=-1 loglevel=8 ignore_loglevel modprobe.blacklist=nouveau nouveau.modeset=0 sevyn.installed=1
  initrd /boot/initramfs.cpio.gz
}

GRUBEOF

  if [ -n "$esp_uuid" ]; then
    cat >> "$outfile" <<GRUBEOF
# Recovery boots from the ESP: it does not depend on the main rootfs.
# No root= is passed — the recovery initramfs never mounts the installed
# system at boot; sevyn.rootuuid= tells recovery where the root partition
# is when an operation explicitly needs it.
menuentry "SevynOS Recovery" {
  search --no-floppy --set=root --fs-uuid $esp_uuid
  linux /EFI/SevynOS/vmlinuz sevyn.recovery=1 sevyn.rootuuid=$root_uuid console=ttyS0,115200 console=tty0 panic=-1 loglevel=4 modprobe.blacklist=nouveau nouveau.modeset=0
  initrd /EFI/SevynOS/recovery-initramfs.cpio.gz
}

GRUBEOF
  else
    cat >> "$outfile" <<GRUBEOF
# Recovery entry for legacy BIOS installs (no ESP): the kernel and the
# recovery initramfs load from /boot on the root filesystem. No root= is
# passed — the recovery initramfs never mounts the installed system at
# boot; sevyn.rootuuid= tells recovery where the root partition is when an
# operation explicitly needs it.
menuentry "SevynOS Recovery" {
  search --no-floppy --set=root --fs-uuid $root_uuid
  linux /boot/vmlinuz sevyn.recovery=1 sevyn.rootuuid=$root_uuid console=ttyS0,115200 console=tty0 panic=-1 loglevel=4 modprobe.blacklist=nouveau nouveau.modeset=0
  initrd /boot/recovery-initramfs.cpio.gz
}

GRUBEOF
  fi
}
