#!/bin/sh
# SevynOS GRUB configuration generator (shared library).
#
# Generates /boot/grub/grub.cfg for installed systems. Used by
# sevyn-installer-chroot.sh at install time and shipped inside the recovery
# initramfs so recovery can regenerate the bootloader configuration after a
# reinstall. Source this file, then call:
#
#   sevyn_write_grub_cfg <outfile> <root-uuid> [esp-uuid]
#
# When <esp-uuid> is given, the "SevynOS Recovery" entry boots the kernel and
# the recovery initramfs from the ESP (EFI/SevynOS/), so a damaged main
# rootfs cannot prevent recovery from starting. Without an ESP (legacy
# BIOS installs) recovery boots from /boot on the root filesystem.
#
# The recovery entries deliberately pass no root=: the recovery initramfs
# never mounts the main rootfs at boot. The installed-system UUID is passed
# as sevyn.rootuuid= so recovery operations (rollback, reset, …) can locate
# the root partition without mounting it first.
#
# Kernel lifecycle overrides (Phase 3 B3, all optional environment):
#
#   SEVYN_KERNEL / SEVYN_INITRAMFS — kernel+initramfs for the three main
#     entries (default: /boot/vmlinuz and /boot/initramfs.cpio.gz).
#   SEVYN_PREV_KERNEL / SEVYN_PREV_INITRAMFS — when BOTH are set, an extra
#     "SevynOS (previous kernel)" fallback entry is written after the
#     diagnostic entry (default: no fallback entry).
#   SEVYN_RECOVERY_KERNEL / SEVYN_RECOVERY_INITRAMFS — kernel+initramfs for
#     the legacy-BIOS recovery entry only (default: /boot/vmlinuz and
#     /boot/recovery-initramfs.cpio.gz). The ESP recovery entry always
#     loads from the ESP's stable names (EFI/SevynOS/vmlinuz and
#     EFI/SevynOS/recovery-initramfs.cpio.gz), which the kernel updater
#     refreshes in lockstep with /boot.
set -eu

# _sevyn_menuentry <title> <kernel> <initramfs> <middle-cmdline> <root-uuid>
# Writes one installed-system boot entry. <middle-cmdline> sits between
# "panic=-1" and the modprobe blacklist, e.g. "loglevel=4" (default),
# "loglevel=4 nomodeset sevyn.gpu=0" (safe graphics),
# "loglevel=8 ignore_loglevel" (diagnostic).
_sevyn_menuentry() {
  _me_title="$1"
  _me_kernel="$2"
  _me_initramfs="$3"
  _me_middle="$4"
  _me_uuid="$5"
  cat <<GRUBEOF
menuentry "$_me_title" {
  search --no-floppy --set=root --fs-uuid $_me_uuid
  linux $_me_kernel root=UUID=$_me_uuid rw init=/init console=ttyS0,115200 console=tty0 panic=-1 $_me_middle modprobe.blacklist=nouveau nouveau.modeset=0 sevyn.installed=1
  initrd $_me_initramfs
}

GRUBEOF
}

sevyn_write_grub_cfg() {
  outfile="$1"
  root_uuid="$2"
  esp_uuid="${3:-}"

  [ -n "$root_uuid" ] || {
    echo "sevyn_write_grub_cfg: root UUID is required" >&2
    return 1
  }

  kernel="${SEVYN_KERNEL:-/boot/vmlinuz}"
  initramfs="${SEVYN_INITRAMFS:-/boot/initramfs.cpio.gz}"

  cat > "$outfile" <<GRUBEOF
# SevynOS GRUB Configuration — Generated by sevyn-installer
insmod part_gpt
insmod ext2
insmod fat
insmod search
insmod search_fs_uuid
insmod all_video

set default=0
set timeout=5

if [ "\$grub_platform" = "pc" ]; then
  set gfxpayload=text
else
  unset gfxpayload
fi

if serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1; then
  terminal_input console serial
  terminal_output console serial
fi

search --no-floppy --set=root --fs-uuid $root_uuid

GRUBEOF

  _sevyn_menuentry "SevynOS" "$kernel" "$initramfs" "loglevel=4" "$root_uuid" >>"$outfile"
  _sevyn_menuentry "SevynOS (safe graphics)" "$kernel" "$initramfs" \
    "loglevel=4 nomodeset sevyn.gpu=0" "$root_uuid" >>"$outfile"
  _sevyn_menuentry "SevynOS (diagnostic)" "$kernel" "$initramfs" \
    "loglevel=8 ignore_loglevel" "$root_uuid" >>"$outfile"

  # Previous-kernel fallback (kernel updates only): the pair the system
  # booted before the update, kept so a broken new kernel still leaves a
  # working boot option.
  if [ -n "${SEVYN_PREV_KERNEL:-}" ] && [ -n "${SEVYN_PREV_INITRAMFS:-}" ]; then
    _sevyn_menuentry "SevynOS (previous kernel)" \
      "$SEVYN_PREV_KERNEL" "$SEVYN_PREV_INITRAMFS" "" "$root_uuid" >>"$outfile"
  fi

  if [ -n "$esp_uuid" ]; then
    cat >> "$outfile" <<GRUBEOF
# Recovery boots from the ESP: it does not depend on the main rootfs.
# No root= is passed — the recovery initramfs never mounts the installed
# system at boot; sevyn.rootuuid= tells recovery where the root partition
# is when an operation explicitly needs it.
menuentry "SevynOS Recovery" {
  search --no-floppy --set=root --fs-uuid $esp_uuid
  linux /EFI/SevynOS/vmlinuz sevyn.recovery=1 sevyn.rootuuid=$root_uuid console=ttyS0,115200 console=tty0 panic=-1 loglevel=4 modprobe.blacklist=nouveau nouveau.modeset=0
  initrd /EFI/SevynOS/recovery-initramfs.cpio.gz
}

GRUBEOF
  else
    rec_kernel="${SEVYN_RECOVERY_KERNEL:-/boot/vmlinuz}"
    rec_initramfs="${SEVYN_RECOVERY_INITRAMFS:-/boot/recovery-initramfs.cpio.gz}"
    cat >> "$outfile" <<GRUBEOF
# Recovery entry for legacy BIOS installs (no ESP): the kernel and the
# recovery initramfs load from /boot on the root filesystem. No root= is
# passed — the recovery initramfs never mounts the installed system at
# boot; sevyn.rootuuid= tells recovery where the root partition is when an
# operation explicitly needs it.
menuentry "SevynOS Recovery" {
  search --no-floppy --set=root --fs-uuid $root_uuid
  linux $rec_kernel sevyn.recovery=1 sevyn.rootuuid=$root_uuid console=ttyS0,115200 console=tty0 panic=-1 loglevel=4 modprobe.blacklist=nouveau nouveau.modeset=0
  initrd $rec_initramfs
}

GRUBEOF
  fi
}
