#!/bin/sh
# SevynOS Installer — Chroot post-installation script
# Runs inside the chroot of the newly installed system.
set -eu

TARGET_DISK="${1:-}"
ESP_DEV="${2:-}"
ROOT_DEV="${3:-}"

log() {
  echo "[sevyn-chroot] $*"
}

fail() {
  log "FATAL: $*"
  exit 1
}

log "Post-installation setup started"
log "Target disk: $TARGET_DISK"
log "ESP: $ESP_DEV"
log "Root: $ROOT_DEV"

# ─── Install GRUB ───────────────────────────────────────────────────
install_grub() {
  log "Installing GRUB bootloader..."
  command -v grub-install >/dev/null 2>&1 || fail "grub-install is missing from the installed system."

  if [ -d /sys/firmware/efi ]; then
    # UEFI mode
    log "Detected UEFI firmware"
      if ! grub-install \
        --target=x86_64-efi \
        --efi-directory=/boot/efi \
        --bootloader-id=SevynOS \
        --recheck \
        "$TARGET_DISK" 2>&1; then
        log "Firmware registration failed; installing a portable UEFI loader."
        grub-install \
          --target=x86_64-efi \
          --efi-directory=/boot/efi \
          --bootloader-id=SevynOS \
          --no-nvram \
          --recheck \
          "$TARGET_DISK" 2>&1 || fail "GRUB UEFI installation failed."
      fi

      # Also install to the removable media path as fallback
      mkdir -p /boot/efi/EFI/BOOT
      if [ -f /boot/efi/EFI/SevynOS/grubx64.efi ] && [ ! -f /boot/efi/EFI/BOOT/BOOTX64.EFI ]; then
        cp /boot/efi/EFI/SevynOS/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI
      fi
  else
    # Legacy BIOS mode
    log "Detected legacy BIOS firmware"
    grub-install --target=i386-pc --recheck "$TARGET_DISK" 2>&1 || fail "GRUB BIOS installation failed."
  fi
}

# ─── Generate GRUB Configuration ────────────────────────────────────
generate_grub_config() {
  log "Generating GRUB configuration..."

  root_uuid=$(blkid -s UUID -o value "$ROOT_DEV" 2>/dev/null || echo "UNKNOWN")
  [ "$root_uuid" != "UNKNOWN" ] && [ -n "$root_uuid" ] || fail "Unable to read the installed root UUID."
  [ -s /boot/vmlinuz ] || fail "Installed kernel is missing."
  [ -s /boot/initramfs.cpio.gz ] || fail "Installed initramfs is missing."

  mkdir -p /boot/grub

  cat > /boot/grub/grub.cfg <<GRUBEOF
# SevynOS GRUB Configuration — Generated by sevyn-installer
insmod part_gpt
insmod ext2
insmod fat
insmod search
insmod search_fs_uuid
insmod all_video

set default=0
set timeout=5

if [ "\$grub_platform" = "pc" ]; then
  set gfxpayload=text
else
  unset gfxpayload
fi

if serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1; then
  terminal_input console serial
  terminal_output console serial
fi

search --no-floppy --set=root --fs-uuid $root_uuid

menuentry "SevynOS" {
  search --no-floppy --set=root --fs-uuid $root_uuid
  linux /boot/vmlinuz root=UUID=$root_uuid rw init=/init console=ttyS0,115200 console=tty0 panic=-1 loglevel=4 modprobe.blacklist=nouveau nouveau.modeset=0 sevyn.installed=1
  initrd /boot/initramfs.cpio.gz
}

menuentry "SevynOS (safe graphics)" {
  search --no-floppy --set=root --fs-uuid $root_uuid
  linux /boot/vmlinuz root=UUID=$root_uuid rw init=/init console=ttyS0,115200 console=tty0 panic=-1 loglevel=4 nomodeset sevyn.gpu=0 modprobe.blacklist=nouveau nouveau.modeset=0 sevyn.installed=1
  initrd /boot/initramfs.cpio.gz
}

menuentry "SevynOS (diagnostic)" {
  search --no-floppy --set=root --fs-uuid $root_uuid
  linux /boot/vmlinuz root=UUID=$root_uuid rw init=/init console=ttyS0,115200 console=tty0 panic=-1 loglevel=8 ignore_loglevel modprobe.blacklist=nouveau nouveau.modeset=0 sevyn.installed=1
  initrd /boot/initramfs.cpio.gz
}

GRUBEOF

  # Detect other operating systems
  if command -v os-prober >/dev/null 2>&1; then
    log "Running os-prober to detect other operating systems..."
    os_entries=$(os-prober 2>/dev/null || true)
    if [ -n "$os_entries" ]; then
      echo "" >> /boot/grub/grub.cfg
      echo "# Other operating systems detected by os-prober" >> /boot/grub/grub.cfg

      echo "$os_entries" | while IFS=: read -r partition name loader type; do
        if [ -z "$partition" ]; then continue; fi
        os_name="${name:-Other OS}"
        log "Found: $os_name on $partition"

        # Get the UUID of the other OS partition
        other_uuid=$(blkid -s UUID -o value "$partition" 2>/dev/null || echo "")

        case "$type" in
          efi)
            cat >> /boot/grub/grub.cfg <<OSEOF

menuentry "$os_name" {
  insmod chain
  insmod fat
  search --no-floppy --set=root --fs-uuid $other_uuid
  chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
OSEOF
            ;;
          linux)
            cat >> /boot/grub/grub.cfg <<OSEOF

menuentry "$os_name" {
  insmod ext2
  search --no-floppy --set=root --fs-uuid $other_uuid
  configfile /boot/grub/grub.cfg
}
OSEOF
            ;;
          *)
            cat >> /boot/grub/grub.cfg <<OSEOF

menuentry "$os_name" {
  insmod chain
  search --no-floppy --set=root --fs-uuid $other_uuid
  chainloader +1
}
OSEOF
            ;;
        esac
      done
    else
      log "No other operating systems detected."
    fi
  fi
}

# ─── Set Timezone ────────────────────────────────────────────────────
configure_system() {
  log "Configuring system..."

  # Set timezone to UTC by default
  if [ -f /usr/share/zoneinfo/UTC ]; then
    ln -sf /usr/share/zoneinfo/UTC /etc/localtime
  fi

  # Ensure essential directories exist
  mkdir -p /var/lib/sevynos
  mkdir -p /var/log
  mkdir -p /tmp
  mkdir -p /media
  mkdir -p /run

  # Set up basic network config
  if [ ! -f /etc/resolv.conf ] || [ ! -s /etc/resolv.conf ]; then
    printf 'nameserver 1.1.1.1\nnameserver 8.8.8.8\n' > /etc/resolv.conf
  fi

  log "System configuration complete."
}

# ─── Main ────────────────────────────────────────────────────────────
install_grub
generate_grub_config
configure_system

log "Post-installation setup complete."
