export type RuntimeErrorCode =
  | "APPLICATION_NOT_FOUND"
  | "APPLICATION_HOST_NOT_FOUND"
  | "APPLICATION_SESSION_NOT_FOUND"
  | "DUPLICATE_APPLICATION"
  | "INVALID_APPLICATION_SESSION_STATE"
  | "INVALID_RUNTIME_STATE"
  | "RUNTIME_SHUTDOWN_FAILED"
  | "INVALID_APPLICATION_MANIFEST"
  | "INVALID_APPLICATION_PACKAGE";
