[package]
name = "sevyn-wayland-bridge"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[profile.release]
strip = true
lto = true
panic = "abort"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smithay-client-toolkit = "0.19.2"
wayland-client = { version = "0.31.11", features = ["system"] }
pollster = "0.4"
raw-window-handle = "0.6"
wgpu = "24"
